def cat_subcat_dicts(dict_name = 'sub'):

    if(dict_name == 'cat'):
        category_id_vs_name = {1: 'Air, Helicopter & Balloon Tours',
         26051: 'Classes & Workshops',
         3: 'Cruises, Sailing & Water Tours',
         4: 'Cultural & Theme Tours',
         5: 'Day Trips & Excursions',
         6: 'Food, Wine & Nightlife',
         7: 'Holiday & Seasonal Tours',
         21: 'Kid Friendly',
         25: 'Luxury & Special Occasions',
         20: 'Multi-day & Extended Tours',
         9: 'Outdoor Activities',
         26: 'Private & Custom Tours',
         10: 'Shopping & Fashion',
         24: 'Shore Excursions',
         11: 'Shows, Concerts & Sports',
         8: 'Sightseeing Tickets & Passes',
         5335: 'Spa Tours',
         14: 'Theme Parks',
         12: 'Tours & Sightseeing',
         15: 'Transfers & Ground Transport',
         50127: 'Unique Experiences',
         5326: 'Viator VIP & Exclusive Tours',
         16: 'Walking & Biking Tours',
         17: 'Water Sports',
         18: 'Weddings & Honeymoons'}
        return category_id_vs_name
        
    elif(dict_name == 'sub'):
        subcat_id_vs_name = {1: 'Air Tours',
         2: 'Helicopter Tours',
         3: 'Balloon Rides',
         121: 'Inter-Island Flights',
         32014: 'Surfing Lessons',
         32012: 'Pottery Classes',
         32008: 'Dance Lessons',
         32009: 'Painting Classes',
         33262: 'Martial Arts Classes',
         33259: 'Glassblowing Classes',
         40286: 'Art Classes',
         40288: 'Music Classes',
         40290: 'Language Classes',
         40293: 'Sports Lessons',
         26052: 'Yoga Classes',
         33939: 'Craft Classes',
         32750: 'Spanish Lessons',
         32016: 'Catamaran Cruises',
         32018: 'Dhow Cruises',
         5638: 'Sunset Cruises',
         5639: 'Lunch Cruises',
         7: 'Day Cruises',
         8: 'Multi-day Cruises',
         9: 'Night Cruises',
         5641: 'Glass Bottom Boat Tours',
         5640: 'Dinner Cruises',
         40295: 'Water Tours',
         10: 'Sailing Trips',
         67: 'Submarine Tours',
         26027: 'Airboat Tours',
         77: 'Dolphin & Whale Watching',
         76: 'Duck Tours',
         26026: 'Brunch Cruises',
         5318: 'Gondola Cruises',
         26973: 'Jewish Tours',
         26971: 'Christian Tours',
         26975: 'Colosseum Underground Tours',
         26969: 'Famous Places In Rome',
         26967: 'Architecture Tours',
         26965: 'Basilica Tours',
         11: 'Cultural Tours',
         13: 'Movie & TV Tours',
         12: 'Historical & Heritage Tours',
         14: 'Literary, Art & Music Tours',
         40338: 'LGBT Friendly Tours',
         27031: 'Ancient Rome Tours',
         118: 'Ghost & Vampire Tours',
         5332: 'Archaeology Tours',
         26930: 'Rome To Capri',
         26938: 'Rome To Amalfi',
         26936: 'Rome To Assisi',
         26934: 'Rome To Siena',
         26932: 'Rome To Tuscany',
         26928: 'Rome To Pisa',
         26926: 'Rome To Positano',
         26924: 'Rome To Sorrento',
         26922: 'Rome To Florence',
         26920: 'Rome To Venice',
         26940: 'Rome To Orvieto',
         26942: 'Rome To Pompeii',
         15: 'Day Trips',
         17: 'Rail Tours',
         26918: 'Trains To Pompeii',
         26916: 'Trains To Florence',
         74: 'Private Day Trips',
         26678: 'Verona Day Trips from Milan',
         26687: 'Genoa Day Trips from Milan',
         26685: 'Italian Riviera Multi Day Trips from Milan',
         26683: 'Swiss Alps Day Trips from Milan',
         26681: 'Venice Day Trips from Milan',
         26689: 'Cinque Terre Day Trips from Milan',
         5635: 'Sake Tasting and Brewery Tours',
         32027: 'Street Food Tours',
         32024: 'Market Tours',
         32022: 'Distillery Tours',
         32020: 'Chocolate Tours',
         19: 'Cooking Classes',
         18: 'Bar, Club & Pub Tours',
         20: 'Dining Experiences',
         21: 'Wine Tasting & Winery Tours',
         79: 'Dinner Theater',
         80: 'Food Tours',
         81: 'Nightlife',
         110: 'Entertainment Packages',
         5324: 'Beer & Brewery Tours',
         5325: 'Coffee & Tea Tours',
         5207: 'Afternoon Teas',
         33120: "Father's Day",
         22: 'Christmas',
         24: "Mother's Day",
         23: 'Halloween',
         26: 'New Years ',
         25: 'National Holidays',
         28: "Valentine's Day",
         27: 'Seasonal Events',
         5333: 'Day of the Dead',
         5334: 'Easter',
         78: 'Kid Friendly Tours & Activities',
         115: 'Once in a Lifetime Experiences',
         114: 'Romantic Tours',
         113: 'Luxury Tours',
         26950: 'Rome in 3 Days',
         26957: '5-Day Tours',
         26955: '4-Day Tours',
         26953: '3-Day Tours',
         26948: 'Rome in 2 Days',
         84: 'Overnight Tours',
         86: 'Multi-day Cruises',
         85: 'Multi-day Tours',
         109: 'Multi-day Rail Tours',
         33264: 'Obstacle Courses',
         40297: 'Other Outdoor Activities',
         33: 'Fishing Charters & Tours',
         32: '4WD, ATV & Off-Road Tours',
         35: 'Hiking & Camping',
         34: 'Golf Tours & Tee Times',
         37: 'Safaris',
         36: 'Nature & Wildlife',
         38: 'Ski & Snow',
         26032: 'Horseback Riding',
         87: 'Adrenaline & Extreme',
         32753: 'Paintball',
         32755: 'Tennis',
         119: 'Eco Tours',
         33293: 'Paragliding',
         5319: 'Climbing',
         5320: 'Lift Tickets',
         5322: 'Running Tours',
         5321: 'Ski & Snowboard Rentals',
         5323: 'Ziplines',
         117: 'Custom Private Tours',
         116: 'Private Sightseeing Tours',
         5209: 'Viator Private Guides',
         39: 'Shopping Passes & Offers',
         40: 'Shopping Tours',
         88: 'Fashion Shows & Tours',
         5530: 'Western Caribbean Shore Excursions',
         5532: 'Southern Caribbean Shore Excursions',
         5528: 'Eastern Caribbean Shore Excursions',
         89: 'Ports of Call Tours',
         4032: 'Port Transfers',
         32038: 'Light & Sound Shows',
         32036: 'Jazz',
         32033: 'Classical Music',
         32040: 'Opera',
         33280: 'Flamenco',
         42: 'Comedy',
         41: 'Concerts & Special Events',
         44: 'Theater, Shows & Musicals',
         43: 'Sporting Events & Packages',
         70: 'Family-friendly Shows ',
         91: 'Adults-only Shows',
         90: 'Dinner Packages',
         32757: 'Ballet',
         124: 'Cirque du Soleil',
         5111: 'Cabaret',
         29: 'Attraction Tickets',
         31: 'Museum Tickets & Passes',
         30: 'Sightseeing Passes',
         40306: 'Sporting Event Tickets & Passes',
         93: 'Zoo Tickets & Passes',
         92: 'Sightseeing Packages',
         111: 'Nightclub Passes',
         26034: 'Onsens',
         5337: 'Hammams & Turkish Baths',
         5336: 'Day Spas',
         5339: 'Roman Baths',
         5338: 'Thermal Spas & Hot Springs',
         5340: 'Arab Baths',
         51: 'Water Parks',
         50: 'Theme Park Tickets & Tours',
         123: 'Universal Theme Parks',
         122: 'Disney® Parks ',
         26959: 'Bike Rentals',
         5611: 'Sustainable Tours',
         32052: 'Trolley Tours',
         32050: 'Sidecar Tours',
         32056: 'Volunteer Tours',
         32054: 'Tuk Tuk Tours',
         26963: 'Audio Guided Tours',
         26961: 'Vespa Rentals',
         32048: 'Pedicab Tours',
         32046: 'Layover Tours',
         32044: 'Escape Games',
         32042: 'Classic Car Tours',
         33282: 'Trikke Tours',
         32760: 'Underground Tours',
         46: 'Segway Tours',
         45: 'Self-guided Tours & Rentals',
         40336: 'Fun and Games',
         26030: 'Plantation Tours',
         75: 'Private Tours',
         26028: 'Photography Tours',
         26029: 'Horse Carriage Rides',
         95: 'Half-day Tours',
         94: 'Full-day Tours',
         97: 'Hop-on Hop-off Tours',
         96: 'Night Tours',
         99: 'City Packages',
         98: 'Bus & Minivan Tours',
         120: 'Vespa, Scooter & Moped Tours',
         5211: 'Super Savers',
         5329: 'Skip-the-Line Tours',
         5331: 'Motorcycle Tours',
         5330: 'City Tours',
         5526: 'Private Transfers',
         32762: 'Private Drivers',
         26914: 'Rome Hotel Port Transfers',
         26912: 'Fiumicino Airport Port Transfers',
         26910: 'Central Rome Port Transfers',
         26908: 'Rome Airport Transfers',
         26906: 'Ciampino Airport Transfers',
         26904: 'Fiumicino Airport Transfers',
         53: 'Airport Parking',
         52: 'Airport & Ground Transfers',
         54: 'Airport Services',
         69: 'Ferry Services',
         26031: 'Airport Lounges',
         40308: 'Transportation Services',
         40311: 'Water Transfers',
         101: 'Rail Services',
         100: 'Bus Services',
         112: 'Port Transfers ',
         26691: 'Milan Ground Transfers',
         50128: 'Unique Experiences',
         5328: 'Viator VIP Tours',
         5327: 'Viator Exclusive Tours',
         55: 'Bike & Mountain Bike Tours',
         56: 'Walking Tours',
         32059: 'Jetpacks',
         28901: 'Scuba Diving',
         32075: 'Flyboarding',
         57: 'Kayaking & Canoeing',
         59: 'Surfing & Windsurfing',
         58: 'Snorkeling',
         60: 'Other Water Sports',
         40334: 'Water Equipment',
         26033: 'Stand Up Paddleboarding',
         108: 'Swim with Dolphins',
         107: 'Jet Boats & Speed Boats',
         106: 'River Rafting & Tubing',
         105: 'Parasailing',
         104: 'Waterskiing & Jetskiing',
         103: 'Boat Rental',
         102: 'Shark Diving',
         33290: 'Float Trips',
         27534: 'White Water Rafting',
         27536: 'Tubing',
         62: 'Honeymoon Packages',
         61: 'Wedding Packages'}
        return subcat_id_vs_name